# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: maven
    - name: Build
      run: mvn -B package --file pom.xml -DskipTests
    - name: Run Unit & Integration Tests
      run: mvn -B verify --file pom.xml
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/*-reports/TEST-*.xml
        reporter: java-junit
        fail-on-error: true

